feat: add "retry/workflow" endpoint
uc-cdis/argo-wrapper pull request #87
Opened 2023-04-12 19:29 UTC by pieterlukasse

Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- [ ] Remove this line if you've changed the title to (PXP-xxxx): <title>

### New Features

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

2023-04-27 16:19 UTC, kmhernan requested changes
Need to discuss

2023-05-11 18:12 UTC, kmhernan commented on src/argowrapper/engine/argo_engine.py
> +        except NotFoundException:
We will probably need to revisit this for other exceptions

2023-05-11 18:16 UTC, kmhernan approved these changes
Approved, although I think you can only "retry" failed workflows, I don't think we check that but it'd probably throw an exception

2023-05-11 18:51 UTC, pieterlukasse commented
@kmhernan that's a good point. Argo returns this: http 400,  {"code":3,"message":"workflow must be Failed/Error to retry"}

2023-05-11 18:56 UTC, merged